YAML

name: Build VS DTP WORD Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Qt 6
      uses: jurplel/install-qt@v3
      with:
        version: '6.5.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64

    - name: Build C++ Executable
      run: cmake --build build --config Release

    - name: Deploy Qt Dependencies
      run: |
        windeployqt --release --compiler-runtime build/Release/VSDTPWord.exe

    - name: Upload Built Application Zip
      uses: actions/upload-artifact@v4
      with:
        name: VS_DTP_WORD_Executable_x64
        path: build/Release/
